/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\ChairC.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ChairC.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['ChairC_Cube006-Mesh'].geometry} material={materials.Red} />
      <mesh geometry={nodes['ChairC_Cube006-Mesh_1'].geometry} material={materials['Material.001']} />
      <mesh geometry={nodes['ChairC_Cube006-Mesh_2'].geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/ChairC.glb')
