/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\Ehs.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Ehs.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="NurbsPath" geometry={nodes.NurbsPath.geometry} material={materials['Material.001']} position={[-0.048, -0.079, 0.119]} />
    </group>
  )
}

useGLTF.preload('/Ehs.glb')
