/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\hi.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hi.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Material.002']} position={[-0.902, -0.022, 0.449]} rotation={[1.606, 0.036, -0.005]} />
    </group>
  )
}

useGLTF.preload('/hi.glb')
