/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\hi_1.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hi_1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Material.002']} position={[-0.902, -0.022, 0.449]} rotation={[1.62, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/hi_1.glb')
