/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\VelvetBeanBag.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/VelvetBeanBag.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} scale={3.992} />
      <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.003']} position={[0, 3.357, 0]} />
      <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[-0.023, 4.743, 0.221]} scale={0.221} />
    </group>
  )
}

useGLTF.preload('/VelvetBeanBag.glb')
