/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\Hello.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as Three from "three"

export function Hello(props) {
  const { nodes, materials } = useGLTF('models/Hello.glb')

  const texture = useTexture('textures/HelloBake.jpg')
  texture.flipY = false
  texture.encoding = Three.sRGBEncoding

  // Set wrapping and filtering options
  texture.wrapS = Three.RepeatWrapping
  texture.wrapT = Three.RepeatWrapping
  texture.minFilter = Three.LinearFilter
  texture.magFilter = Three.LinearFilter

  const textureMaterial = new Three.MeshStandardMaterial({
    map: texture,
    // Additional settings to ensure the texture is correctly applied
    side: Three.DoubleSide, // If your mesh is double-sided
    transparent: true, // If your texture has an alpha channel
  })


  return (
    <group {...props} dispose={null}>
      <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Material.001']} position={[0, 0.15, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/Hello.glb')
