/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\hi.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as Three from "three"

export function Hi(props) {
  const { nodes, materials } = useGLTF('models/hi_2.glb')

    const texture = useTexture('textures/bake18.jpg')
    texture.flipY = false
    texture.encoding = Three.sRGBEncoding

    const textureMaterial = new Three.MeshStandardMaterial({
      map: texture,
    })

  return (
    <group {...props} dispose={null}>
    <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Material.002']} position={[-0.902, -0.022, 0.449]} rotation={[1.62, 0, 0]} scale={1.083} />
  </group>
  )
}

useGLTF.preload('models/hi_2.glb')

