/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\Eletter.glb -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as Three from "three"

export function Eletter(props) {
  const { nodes, materials } = useGLTF('models/ELetter_2.glb')

  const texture = useTexture('textures/EBake5.jpg')
  texture.flipY = false
  texture.encoding = Three.sRGBEncoding

  const textureMaterial = new Three.MeshStandardMaterial({
    map: texture,
  })


  return (
    <group {...props} dispose={null}>
      <mesh name="Text" geometry={nodes.Text.geometry} material={materials['Material.001']} rotation={[1.594, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/ELetter_2.glb')
